services:
#    music.example:
#        class: MusicBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  app.twig_extension:
          class: MusicBundle\Twig\AppExtension
          public: false
          tags:
              - { name: twig.extension }